version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - 8000:80
    volumes:
      - static_volume:/RD_Motors/RDmotors/static
      - media_volume:/RD_Motors/RDmotors/media
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    working_dir: /RD_Motors/RDmotors
    command: gunicorn RDmotors.wsgi -b 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/RD_Motors/RDmotors/static
      - media_volume:/RD_Motors/RDmotors/media
    depends_on:
      - db

  db:
    image: postgres:12.14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_data:/docker-entrypoint-initdb.d
    env_file:
      - .env.db

volumes:
  postgres_data:
  static_volume:
  media_volume:
