version: '3.7'

services:
  web:
    build: ./
    working_dir: /RD_Motors/RDmotors
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:12.14-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maindb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_data:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
